In [ ]:
python train.py --data colon --snapshot_path "snapshot" --data_prefix "dataset/Task10_Colon" 

In [1]:
import numpy as np
import torch
seg = torch.ones(1,128,128,128)
l = len(torch.where(seg == 1)[0])
print(l)
sample = np.random.choice(np.arange(l), 10, replace=True) # 從範圍為 [0, l) 的整數中隨機選取 10 個數字（可能有重複）
print(sample)
x = torch.where(seg == 1)[1][sample].unsqueeze(1)
y = torch.where(seg == 1)[3][sample].unsqueeze(1)
z = torch.where(seg == 1)[2][sample].unsqueeze(1)
print(z)
point_coord = torch.cat([x, y, z], dim=1).unsqueeze(1).float() 

foo = torch.randn(1,20,3)
point_coord = point_coord.transpose(0,1)
point_coord = torch.cat([point_coord,foo],dim=1)
print(point_coord.size())

point_coord.reshape(1,1,1,-1,3).size()

2097152
[ 940785 1887671  907095  510941 1211251 1157562 1431325 1086533  838822
   24127]
tensor([[ 53],
        [ 27],
        [ 46],
        [ 23],
        [118],
        [ 83],
        [ 46],
        [ 40],
        [ 25],
        [ 60]])
torch.Size([1, 30, 3])


torch.Size([1, 1, 1, 30, 3])

In [2]:
x = torch.randn(3, 2)
print(x)
torch.where(x > 0)

tensor([[ 0.0637, -0.6329],
        [-0.6641, -1.6162],
        [-1.0634,  1.4174]])


(tensor([0, 2]), tensor([0, 1]))

In [3]:
x = torch.randn(10,1)
y = torch.randn(10,1)
z = torch.randn(10,1)
points = torch.cat([x, y, z], dim=1).unsqueeze(1).float()
print(points.size())
points= points.transpose(0,1)
a = torch.randn(1,10,3)
print(a.size())
print(points.size())
torch.cat([a,points],dim=1).size()

torch.Size([10, 1, 3])
torch.Size([1, 10, 3])
torch.Size([1, 10, 3])


torch.Size([1, 20, 3])

In [4]:
import torch.nn.functional as F
img = torch.randn(1,3, 128,128,128)
# img[:, 0].size()
F.interpolate(img,scale_factor=0.5,mode='trilinear').size()

torch.Size([1, 3, 64, 64, 64])